package com.taca.mapper;


import com.taca.model.GoodsInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    GoodsInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_GOODS_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKey(GoodsInfo record);
}