package com.taca.mapper;


import com.taca.model.NoticeInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface NoticeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insert(NoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insertSelective(NoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    NoticeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(NoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(NoticeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_NOTICE_INFO
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKey(NoticeInfo record);
}