package com.taca.mapper;


import com.taca.model.ReciveTask;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ReciveTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insert(ReciveTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insertSelective(ReciveTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    ReciveTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(ReciveTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ReciveTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_RECIVE_TASK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKey(ReciveTask record);
}