package com.taca.mapper;


import com.taca.model.Submissions;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SubmissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_SUBMISSIONS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_SUBMISSIONS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insert(Submissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_SUBMISSIONS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insertSelective(Submissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_SUBMISSIONS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    Submissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_SUBMISSIONS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(Submissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_SUBMISSIONS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKey(Submissions record);
}