package com.taca.mapper;


import com.taca.model.TaskMutex;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TaskMutexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_TASK_MUTEX
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_TASK_MUTEX
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insert(TaskMutex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_TASK_MUTEX
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insertSelective(TaskMutex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_TASK_MUTEX
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    TaskMutex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_TASK_MUTEX
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(TaskMutex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_B_TASK_MUTEX
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKey(TaskMutex record);
}