package com.taca.mapper;


import com.taca.model.TransRecord;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TransRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_TRANS_RECORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_TRANS_RECORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insert(TransRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_TRANS_RECORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int insertSelective(TransRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_TRANS_RECORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    TransRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_TRANS_RECORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKeySelective(TransRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_D_TRANS_RECORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    int updateByPrimaryKey(TransRecord record);
}