package com.taca.model;

import org.apache.ibatis.type.Alias;

import java.util.Date;
@Alias("GoodsInfo")
public class GoodsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.TYPE
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.CATEGORY
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long starNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.STAR_LEVEL
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long starLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.ICON_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String iconAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.STATUS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.COUNT
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.AVAILABLE_STOCK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long availableStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_GOODS_INFO.DESCRIPTION
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.ID
     *
     * @return the value of IM_B_GOODS_INFO.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.ID
     *
     * @param id the value for IM_B_GOODS_INFO.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.TYPE
     *
     * @return the value of IM_B_GOODS_INFO.TYPE
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.TYPE
     *
     * @param type the value for IM_B_GOODS_INFO.TYPE
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.CATEGORY
     *
     * @return the value of IM_B_GOODS_INFO.CATEGORY
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.CATEGORY
     *
     * @param category the value for IM_B_GOODS_INFO.CATEGORY
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.NAME
     *
     * @return the value of IM_B_GOODS_INFO.NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.NAME
     *
     * @param name the value for IM_B_GOODS_INFO.NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.STAR_NUMBER
     *
     * @return the value of IM_B_GOODS_INFO.STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getStarNumber() {
        return starNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.STAR_NUMBER
     *
     * @param starNumber the value for IM_B_GOODS_INFO.STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setStarNumber(Long starNumber) {
        this.starNumber = starNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.STAR_LEVEL
     *
     * @return the value of IM_B_GOODS_INFO.STAR_LEVEL
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.STAR_LEVEL
     *
     * @param starLevel the value for IM_B_GOODS_INFO.STAR_LEVEL
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setStarLevel(Long starLevel) {
        this.starLevel = starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.ICON_ADDRESS
     *
     * @return the value of IM_B_GOODS_INFO.ICON_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getIconAddress() {
        return iconAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.ICON_ADDRESS
     *
     * @param iconAddress the value for IM_B_GOODS_INFO.ICON_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setIconAddress(String iconAddress) {
        this.iconAddress = iconAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.STATUS
     *
     * @return the value of IM_B_GOODS_INFO.STATUS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.STATUS
     *
     * @param status the value for IM_B_GOODS_INFO.STATUS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.COUNT
     *
     * @return the value of IM_B_GOODS_INFO.COUNT
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.COUNT
     *
     * @param count the value for IM_B_GOODS_INFO.COUNT
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.AVAILABLE_STOCK
     *
     * @return the value of IM_B_GOODS_INFO.AVAILABLE_STOCK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getAvailableStock() {
        return availableStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.AVAILABLE_STOCK
     *
     * @param availableStock the value for IM_B_GOODS_INFO.AVAILABLE_STOCK
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setAvailableStock(Long availableStock) {
        this.availableStock = availableStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.CREATE_TIME
     *
     * @return the value of IM_B_GOODS_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.CREATE_TIME
     *
     * @param createTime the value for IM_B_GOODS_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.UPDATE_TIME
     *
     * @return the value of IM_B_GOODS_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.UPDATE_TIME
     *
     * @param updateTime the value for IM_B_GOODS_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_GOODS_INFO.DESCRIPTION
     *
     * @return the value of IM_B_GOODS_INFO.DESCRIPTION
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_GOODS_INFO.DESCRIPTION
     *
     * @param description the value for IM_B_GOODS_INFO.DESCRIPTION
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}