package com.taca.model;

import org.apache.ibatis.type.Alias;

import java.util.Date;
@Alias("ReciveTask")
public class ReciveTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.TASK_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.ACT_STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long actStarNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.PRE_STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long preStarNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.STATUS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.TRANS_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long transId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.START_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.EXPECTED_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date expectedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.FINISHED_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date finishedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_RECIVE_TASK.CONTENT
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.ID
     *
     * @return the value of IM_D_RECIVE_TASK.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.ID
     *
     * @param id the value for IM_D_RECIVE_TASK.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.TASK_ID
     *
     * @return the value of IM_D_RECIVE_TASK.TASK_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.TASK_ID
     *
     * @param taskId the value for IM_D_RECIVE_TASK.TASK_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.NAME
     *
     * @return the value of IM_D_RECIVE_TASK.NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.NAME
     *
     * @param name the value for IM_D_RECIVE_TASK.NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.ACT_STAR_NUMBER
     *
     * @return the value of IM_D_RECIVE_TASK.ACT_STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getActStarNumber() {
        return actStarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.ACT_STAR_NUMBER
     *
     * @param actStarNumber the value for IM_D_RECIVE_TASK.ACT_STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setActStarNumber(Long actStarNumber) {
        this.actStarNumber = actStarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.PRE_STAR_NUMBER
     *
     * @return the value of IM_D_RECIVE_TASK.PRE_STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getPreStarNumber() {
        return preStarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.PRE_STAR_NUMBER
     *
     * @param preStarNumber the value for IM_D_RECIVE_TASK.PRE_STAR_NUMBER
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setPreStarNumber(Long preStarNumber) {
        this.preStarNumber = preStarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.STATUS
     *
     * @return the value of IM_D_RECIVE_TASK.STATUS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.STATUS
     *
     * @param status the value for IM_D_RECIVE_TASK.STATUS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.TRANS_ID
     *
     * @return the value of IM_D_RECIVE_TASK.TRANS_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.TRANS_ID
     *
     * @param transId the value for IM_D_RECIVE_TASK.TRANS_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setTransId(Long transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.START_TIME
     *
     * @return the value of IM_D_RECIVE_TASK.START_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.START_TIME
     *
     * @param startTime the value for IM_D_RECIVE_TASK.START_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.EXPECTED_TIME
     *
     * @return the value of IM_D_RECIVE_TASK.EXPECTED_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getExpectedTime() {
        return expectedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.EXPECTED_TIME
     *
     * @param expectedTime the value for IM_D_RECIVE_TASK.EXPECTED_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setExpectedTime(Date expectedTime) {
        this.expectedTime = expectedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.FINISHED_TIME
     *
     * @return the value of IM_D_RECIVE_TASK.FINISHED_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getFinishedTime() {
        return finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.FINISHED_TIME
     *
     * @param finishedTime the value for IM_D_RECIVE_TASK.FINISHED_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setFinishedTime(Date finishedTime) {
        this.finishedTime = finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.CREATE_TIME
     *
     * @return the value of IM_D_RECIVE_TASK.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.CREATE_TIME
     *
     * @param createTime the value for IM_D_RECIVE_TASK.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.UPDATE_TIME
     *
     * @return the value of IM_D_RECIVE_TASK.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.UPDATE_TIME
     *
     * @param updateTime the value for IM_D_RECIVE_TASK.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_RECIVE_TASK.CONTENT
     *
     * @return the value of IM_D_RECIVE_TASK.CONTENT
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_RECIVE_TASK.CONTENT
     *
     * @param content the value for IM_D_RECIVE_TASK.CONTENT
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}