package com.taca.model;

import org.apache.ibatis.type.Alias;

import java.util.Date;

@Alias("Submissions")
public class Submissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_SUBMISSIONS.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_SUBMISSIONS.RECEIVE_TASK_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long receiveTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_SUBMISSIONS.FILE_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String fileAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_SUBMISSIONS.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_SUBMISSIONS.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_SUBMISSIONS.ID
     *
     * @return the value of IM_D_SUBMISSIONS.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_SUBMISSIONS.ID
     *
     * @param id the value for IM_D_SUBMISSIONS.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_SUBMISSIONS.RECEIVE_TASK_ID
     *
     * @return the value of IM_D_SUBMISSIONS.RECEIVE_TASK_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getReceiveTaskId() {
        return receiveTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_SUBMISSIONS.RECEIVE_TASK_ID
     *
     * @param receiveTaskId the value for IM_D_SUBMISSIONS.RECEIVE_TASK_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setReceiveTaskId(Long receiveTaskId) {
        this.receiveTaskId = receiveTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_SUBMISSIONS.FILE_ADDRESS
     *
     * @return the value of IM_D_SUBMISSIONS.FILE_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getFileAddress() {
        return fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_SUBMISSIONS.FILE_ADDRESS
     *
     * @param fileAddress the value for IM_D_SUBMISSIONS.FILE_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_SUBMISSIONS.CREATE_TIME
     *
     * @return the value of IM_D_SUBMISSIONS.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_SUBMISSIONS.CREATE_TIME
     *
     * @param createTime the value for IM_D_SUBMISSIONS.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_SUBMISSIONS.UPDATE_TIME
     *
     * @return the value of IM_D_SUBMISSIONS.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_SUBMISSIONS.UPDATE_TIME
     *
     * @param updateTime the value for IM_D_SUBMISSIONS.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}