package com.taca.model;

import org.apache.ibatis.type.Alias;

import java.util.Date;
@Alias("TaskMutex")
public class TaskMutex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_TASK_MUTEX.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_TASK_MUTEX.TASK_FIRST_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long taskFirstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_TASK_MUTEX.TASK_SECOND_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long taskSecondId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_TASK_MUTEX.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_B_TASK_MUTEX.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_TASK_MUTEX.ID
     *
     * @return the value of IM_B_TASK_MUTEX.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_TASK_MUTEX.ID
     *
     * @param id the value for IM_B_TASK_MUTEX.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_TASK_MUTEX.TASK_FIRST_ID
     *
     * @return the value of IM_B_TASK_MUTEX.TASK_FIRST_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getTaskFirstId() {
        return taskFirstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_TASK_MUTEX.TASK_FIRST_ID
     *
     * @param taskFirstId the value for IM_B_TASK_MUTEX.TASK_FIRST_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setTaskFirstId(Long taskFirstId) {
        this.taskFirstId = taskFirstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_TASK_MUTEX.TASK_SECOND_ID
     *
     * @return the value of IM_B_TASK_MUTEX.TASK_SECOND_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getTaskSecondId() {
        return taskSecondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_TASK_MUTEX.TASK_SECOND_ID
     *
     * @param taskSecondId the value for IM_B_TASK_MUTEX.TASK_SECOND_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setTaskSecondId(Long taskSecondId) {
        this.taskSecondId = taskSecondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_TASK_MUTEX.CREATE_TIME
     *
     * @return the value of IM_B_TASK_MUTEX.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_TASK_MUTEX.CREATE_TIME
     *
     * @param createTime the value for IM_B_TASK_MUTEX.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_B_TASK_MUTEX.UPDATE_TIME
     *
     * @return the value of IM_B_TASK_MUTEX.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_B_TASK_MUTEX.UPDATE_TIME
     *
     * @param updateTime the value for IM_B_TASK_MUTEX.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}