package com.taca.model;

import org.apache.ibatis.type.Alias;

import java.util.Date;
@Alias("UserInfo")
public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.USER_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.NICK_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.USER_NAME_CN
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String userNameCn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.PASSWORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.WX_OPEN_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String wxOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.AVAILABLE_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long availableStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.EMAIL_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.FREEZE_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long freezeStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.HISTORY_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long historyStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.GROUP_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.GROUP_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.HONOR_TITLE
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String honorTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.UM
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private String um;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_D_USER_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.ID
     *
     * @return the value of IM_D_USER_INFO.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.ID
     *
     * @param id the value for IM_D_USER_INFO.ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.USER_NAME
     *
     * @return the value of IM_D_USER_INFO.USER_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.USER_NAME
     *
     * @param userName the value for IM_D_USER_INFO.USER_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.NICK_NAME
     *
     * @return the value of IM_D_USER_INFO.NICK_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.NICK_NAME
     *
     * @param nickName the value for IM_D_USER_INFO.NICK_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.USER_NAME_CN
     *
     * @return the value of IM_D_USER_INFO.USER_NAME_CN
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getUserNameCn() {
        return userNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.USER_NAME_CN
     *
     * @param userNameCn the value for IM_D_USER_INFO.USER_NAME_CN
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUserNameCn(String userNameCn) {
        this.userNameCn = userNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.PASSWORD
     *
     * @return the value of IM_D_USER_INFO.PASSWORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.PASSWORD
     *
     * @param password the value for IM_D_USER_INFO.PASSWORD
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.WX_OPEN_ID
     *
     * @return the value of IM_D_USER_INFO.WX_OPEN_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.WX_OPEN_ID
     *
     * @param wxOpenId the value for IM_D_USER_INFO.WX_OPEN_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.AVAILABLE_STAR
     *
     * @return the value of IM_D_USER_INFO.AVAILABLE_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getAvailableStar() {
        return availableStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.AVAILABLE_STAR
     *
     * @param availableStar the value for IM_D_USER_INFO.AVAILABLE_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setAvailableStar(Long availableStar) {
        this.availableStar = availableStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.EMAIL_ADDRESS
     *
     * @return the value of IM_D_USER_INFO.EMAIL_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.EMAIL_ADDRESS
     *
     * @param emailAddress the value for IM_D_USER_INFO.EMAIL_ADDRESS
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.FREEZE_STAR
     *
     * @return the value of IM_D_USER_INFO.FREEZE_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getFreezeStar() {
        return freezeStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.FREEZE_STAR
     *
     * @param freezeStar the value for IM_D_USER_INFO.FREEZE_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setFreezeStar(Long freezeStar) {
        this.freezeStar = freezeStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.HISTORY_STAR
     *
     * @return the value of IM_D_USER_INFO.HISTORY_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getHistoryStar() {
        return historyStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.HISTORY_STAR
     *
     * @param historyStar the value for IM_D_USER_INFO.HISTORY_STAR
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setHistoryStar(Long historyStar) {
        this.historyStar = historyStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.GROUP_ID
     *
     * @return the value of IM_D_USER_INFO.GROUP_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.GROUP_ID
     *
     * @param groupId the value for IM_D_USER_INFO.GROUP_ID
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.GROUP_NAME
     *
     * @return the value of IM_D_USER_INFO.GROUP_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.GROUP_NAME
     *
     * @param groupName the value for IM_D_USER_INFO.GROUP_NAME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.HONOR_TITLE
     *
     * @return the value of IM_D_USER_INFO.HONOR_TITLE
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getHonorTitle() {
        return honorTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.HONOR_TITLE
     *
     * @param honorTitle the value for IM_D_USER_INFO.HONOR_TITLE
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setHonorTitle(String honorTitle) {
        this.honorTitle = honorTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.UM
     *
     * @return the value of IM_D_USER_INFO.UM
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public String getUm() {
        return um;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.UM
     *
     * @param um the value for IM_D_USER_INFO.UM
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUm(String um) {
        this.um = um;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.CREATE_TIME
     *
     * @return the value of IM_D_USER_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.CREATE_TIME
     *
     * @param createTime the value for IM_D_USER_INFO.CREATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_D_USER_INFO.UPDATE_TIME
     *
     * @return the value of IM_D_USER_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_D_USER_INFO.UPDATE_TIME
     *
     * @param updateTime the value for IM_D_USER_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu Sep 21 18:03:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}